version: '2'

networks:
  logstash-kafka:
    external: true

services:
  zookeeper:
    networks:
      - logstash-kafka
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    networks:
      - logstash-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "app-visits:1:1"
  elasticsearch:
    image: elasticsearch:7.3.1
    networks:
      - logstash-kafka
    volumes: 
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    command: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: logstash:7.3.1
    networks:
      - logstash-kafka
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
      - kafka
    volumes:
      - ./config:/config
    command: logstash -f /config/logstash-kafka-es.conf
