version: '2'

services:
 mysql:
  image: mysql:5.7
  container_name: mysql
  volumes:
    - /Users/linmac/Documents/backup/datafiles:/var/lib/mysql
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=test
    - MYSQL_USER=root
    - MYSQL_PASSWORD=password
  ports:
    - "3306:3306"
