version: '3'

networks:
  my-network:
    external: true

services:
  syslog:
    image: balabit/syslog-ng:latest
    command: --no-caps -edv
    networks:
      - my-network
    ports:
      - 601:601
      - 6514:6514
      - 514:514/udp
    volumes:
      - ./config/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - ./logs:/var/log/syslog-ng"
      - ./socket:/var/run/syslog-ng"