version: '2'

networks:
  my-network:
    external: true

services:
  logstash:
    image: logstash:6.5.1
    ports:
      - 6782:6782
    networks:
      - my-network
    external_links:
      - elasticsearch
    volumes:
      - ./config:/config
    #   - /Users/linzhang/Downloads/file.log:/tmp/file.log
    command: logstash -f /config/logstash.conf

